### ISSUE TITLE
@corebot lock not working

### ISSUE THREAD

**Issue by bluridium** [outofcoffee/corebot#1]
I'm unable to get any @corebot lock commands to work. I have a bunch of actions tagged with 

    tags:
      - wildfly

and when I issue `@corebot lock wildfly` it returns `Sorry, I didn't understand :confused: Try typing _@corebot help_ for examples.` 

`@corebot lock all` returns the same error.

**Comment by outofcoffee** [comment]
Hello @bluridium. Sorry to hear that you're having trouble. To help the diagnosis, please could you post the full logs and the entire config file?

Thanks!

**Comment by bluridium** [comment]
My bad. Needed more coffee this morning. Here are logs from my lock command:

https://gist.github.com/bluridium/74ef6c03bd55dfed875916ccdb3023e1

I'll update the other issue with logs from the security issue.

**Comment by outofcoffee** [comment]
Thanks for the report, @bluridium. This issue is fixed in 555fc52f53f7dcd0588c5fd2f3007721c747c466. I'll look at the security config issue separately.
