### ISSUE TITLE
Trying to pass command options with spaces

### ISSUE THREAD

**Issue by anojansivarajah** [outofcoffee/corebot#10]
Tried to pass option arguments with spaces with no luck as bot cannot understand even if i single or double quote or escape the spaces in the argument

**Comment by anojansivarajah** [comment]
May be a clever splitting here https://github.com/outofcoffee/corebot/blob/master/bot/src/main/kotlin/com/gatehill/corebot/chat/ChatService.kt#L55

**Comment by anojansivarajah** [comment]
https://github.com/outofcoffee/corebot/pull/11

**Comment by outofcoffee** [comment]
Thanks @anojansivarajah. A shame that the single quotes didn't work for you - it does seem to work OK for us. I'll have a look at the PR you raised.

**Comment by anojansivarajah** [comment]
@outofcoffee @pcornish Have you had a chance yet?

**Comment by outofcoffee** [comment]
Fixed in v0.7.0.

Thanks, @anojansivarajah .
