### ISSUE TITLE
cannot run using lastest..

### ISSUE THREAD

**Issue by ThomasADavis** [outofcoffee/corebot#14]
I am getting this error:

22:31:48.652 [Grizzly(2)] DEBUG com.gatehill.corebot.security.AuthorisationService - User 'tadavis' action TRIGGER: PERMITTED
22:31:48.880 [Grizzly(2)] INFO  com.gatehill.corebot.action.BaseJobTriggerService - Triggering action: status with job ID: c7f06409-68d5-4dd1-a960-c92733eed12e and args: {vmname=rabbit-3}
22:31:49.174 [OkHttp https://rundeck.nersc.gov/...] ERROR com.gatehill.corebot.driver.rundeck.action.RundeckJobTriggerService - Unsuccessfully triggered job with ID: c7f06409-68d5-4dd1-a960-c92733eed12e and args: {vmname=rabbit-3} - response: {"error":true,"apiversion":18,"errorCode":"api.error.item.unauthorized","message":"Not authorized for action \"Run as User\" for Job ID c7f06409-68d5-4dd1-a960-c92733eed12e"}
22:31:49.174 [OkHttp https://rundeck.nersc.gov/...] ERROR com.gatehill.corebot.chat.SlackChatServiceImpl - Error performing custom action CustomAction(actionType=TRIGGER, actionConfig=ActionConfig(name='status', jobId='c7f06409-68d5-4dd1-a960-c92733eed12e', options={}, template='vm status {vmname}', tags=[all, dae], driver='rundeck', showJobOutput='true', showJobOutcome='true'), args={vmname=rabbit-3})
java.lang.RuntimeException: {"error":true,"apiversion":18,"errorCode":"api.error.item.unauthorized","message":"Not authorized for action \"Run as User\" for Job ID c7f06409-68d5-4dd1-a960-c92733eed12e"}
	at com.gatehill.corebot.driver.rundeck.action.RundeckJobTriggerService$triggerExecution$1.onResponse(RundeckJobTriggerService.kt:71) [rundeck-0.7.0.jar:?]
	at retrofit2.OkHttpCall$1.callSuccess(OkHttpCall.java:132) [retrofit-2.1.0.jar:?]
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:111) [retrofit-2.1.0.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133) [okhttp-3.3.0.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.3.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

and I have no idea how to fix it.

Everything worked in the previous version.

**Comment by outofcoffee** [comment]
Hi @ThomasADavis - thanks for raising this. Looks like the `runAsTriggerUser` behaviour should be disabled by default. Please could you try out v0.7.1 and see if that resolves your issue?

**Comment by anojansivarajah** [comment]
Api token needs runasuser permission.
http://rundeck.org/docs/administration/access-control-policy.html

**Comment by outofcoffee** [comment]
Thanks @anojansivarajah. I've gone with the safer option of requiring users to opt-in with the config setting `runAsTriggerUser` so we maintain backwards compatibility.

**Comment by outofcoffee** [comment]
We should document how to enable it (and add the link you provided above).

**Comment by ThomasADavis** [comment]
thanks for the fast response!

that fixed it, everything works again like before.

I'll have to re-visit the API acl's..
