### ISSUE TITLE
Feature: Ability to switch on and off reply in thread

### ISSUE THREAD

**Issue by anojansivarajah** [outofcoffee/corebot#15]
I would like to have the above feature turned on and off by environment variable called REPLY_IN_THREAD: Boolean.
This means where ever we are using
      ` com.ullink.slack.simpleslackapi.SlackSession.sendMessage(SlackChannel, String)` 
we need to change it to use
      ` com.ullink.slack.simpleslackapi.SlackSession.sendMessage(SlackChannel, SlackPreparedMessage)`
 and create SlackPreparedMessage with the builder in that class
       (`com.ullink.slack.simpleslackapi.SlackPreparedMessage`)

Additionally triggerContext need to have thread_ts

PS: this will only work with the latest commit of simple-slack-api which means we need to update
        ext.version_slackapi = '0c58385'

@pcornish @outofcoffee  Any comments? Pull request https://github.com/outofcoffee/corebot/pull/16

**Comment by outofcoffee** [comment]
This is a great idea!

**Comment by anojansivarajah** [comment]
So can we have it? Pullrequest is ready

**Comment by outofcoffee** [comment]
Thanks; I will review the PR.

**Comment by outofcoffee** [comment]
Fixed in #22. Thanks @anojansivarajah
