### ISSUE TITLE
Corebot does not start with security: block in config

### ISSUE THREAD

**Issue by bluridium** [outofcoffee/corebot#2]
When adding the following to my actions.yml config file the corebot container starts and immediately exits.

    security:
      users:
        alice:
          roles:
            - admin

**Comment by outofcoffee** [comment]
Hello @bluridium. Sorry to hear that you're having trouble. To help the diagnosis, please could you post the full logs and the entire config file?

Thanks!

**Comment by bluridium** [comment]
Sure can. Where are the logs located?

**Comment by outofcoffee** [comment]
It depends on how you are running corebot. If you're using Docker, then they should be on the command line, if you started it with a TTY; alternatively you could do `docker logs <container name or ID>`

**Comment by bluridium** [comment]
My bad. Needed more coffee this morning. Here are logs from startup with the security: block in place. 

https://gist.github.com/bluridium/25be13a2a63418f461c3a9d26ed327c8

Here is the actions.yml with security:

https://gist.github.com/bluridium/15368ef4681e408ed83f48c004155e85

**Comment by outofcoffee** [comment]
Thanks for the report, @bluridium. This issue is fixed in v0.6.2.
