### ISSUE TITLE
Option to disable slack greeting on startup

### ISSUE THREAD

**Issue by mumblez** [outofcoffee/corebot#53]
Apologies if there's an option for this but I can't seem to find it, is there a way to disable / silent the initial slack greeting when corebot starts up?

**Comment by outofcoffee** [comment]
Hi @mumblez, thanks for raising this. The documentation could be better.

You can set `joinMessage` to an empty string in your action configuration file to accomplish this.

**Comment by mumblez** [comment]
@outofcoffee it works, thanks for your help :)
